"""Getting Bricks into the Library — the script the proposal document is built from.

The proposal answers a constraint Glen stated 2026-08-26: the consortium has no staff to answer
part requests from dozens of students, so getting a part into a library must be self-service.
House formatting comes from makedocx, imported from Sangala Studio's tools so the three
applications' documents cannot drift into three formats.
"""
import sys
sys.path.insert(0, r"D:\Code Projects\Silhouette Tools\tools")
from makedocx import Doc

OUT = r"C:\Users\glenb\UVa Lab School Dropbox\AI Sandbox\Design through Making\_Drafts"

d = Doc()
d.title("Getting Bricks into the Library")

d.body("Sangala Blocks plans a figure built from real LEGO bricks and then orders the parts. The order "
       "comes after the design, so a builder works with parts not yet owned, and the parts themselves "
       "are discovered where they will be bought — LEGO's Pick a Brick catalog. Every part the "
       "application offers has so far entered its libraries through the consortium: scripts run over "
       "the full LDraw parts library and LEGO element data, with each derived entry checked by eye. "
       "None of that tooling ships with the application, and a program serving dozens of students "
       "cannot route requests for missing parts through staff. This document proposes two mechanisms, "
       "both self-service, that remove the consortium from the path.")

d.heading("The Present Route, and Why It Stops Short")
d.body("A library file is produced on the consortium side. The measuring tools resolve each design "
       "number against the full LDraw parts library — 24,591 part files, roughly 650 MB — and against "
       "the Rebrickable element data that makes a part orderable in a given color. The application "
       "ships a 9.7 MB excerpt of LDraw: the 39 parts already offered, with their shared sub-files. "
       "A student can merge and prune existing libraries — open several, then Save, Library — but "
       "cannot introduce a part that no library holds.")
d.body("Ordering has the same boundary. The order export fills each row's element ID from a table "
       "baked into the page, currently 427 entries covering the parts and palette colors the "
       "application knows. A part outside that table designs correctly and then drops out of the "
       "order.")
d.body("The African Buffalo kit inventory makes the scale of the need concrete. Its 82 pieces are all "
       "ordinary bricks, plates, and slopes — no exotic molds — yet several of its design numbers "
       "(3037, 3660, 3666, 3009, and the 3867 baseplate) appear in no shipped library. What students "
       "will run out of is breadth, not strangeness.")

d.heading("Mechanism One: a Shipped Catalog")
d.body("One library file, generated by machine on the consortium side and shipped with the "
       "application, covering every part LEGO commonly sells in the ordinary families — bricks, "
       "plates, slopes, wedges, rounds, cones, tiles, and baseplates. The generation is the existing "
       "curation run wider: on the order of one to a few thousand entries, at roughly 180 bytes an "
       "entry, so the file is measured in hundreds of kilobytes. It travels in the distribution "
       "folder and updates like any other file; a part found missing improves the next shipped "
       "catalog for everyone rather than one student's copy.")
d.body("Three consequences follow for the application.", before_list=True)
d.item("Search. ", "The Library section gains a search field. Typing filters the rows by name or "
       "design number, so a student wanting a slope searches inside the application the same way "
       "Pick a Brick is searched — and writes to no one.")
d.item("The Part Menu Is Protected. ", "A library deliberately extends the Part tool's menu; a "
       "thousand sizes would bury it. The catalog file carries a marker, and a marked catalog serves "
       "the searchable panel only. Its parts place by dragging a row onto the workspace, exactly as "
       "library parts place today.")
d.item("Ordering Travels with It. ", "The same generation sweep attaches each part's element ID in "
       "each palette color, from the Rebrickable data, written into the file. The order export "
       "consults loaded libraries as well as the built-in table, and an entry with no orderable "
       "element in the chosen color is named at export rather than silently dropped.")
d.body("The generator carries its own acceptance test, in the pattern the element table established: "
       "it refuses to write unless every part of the African Buffalo kit inventory, of Jo Watts's "
       "75-part list, and of the crane resolves — findable by search, orderable in its kit color.")

d.heading("Mechanism Two: Add Part by Hand")
d.body("For the tail the catalog misses. A small control on the Library section takes what the "
       "Pick a Brick page states about a part: the design number, the name, the shape chosen from "
       "the application's short list, the footprint in studs, the height in plates, and the element "
       "ID for the chosen color. The part joins the library, places from its row, and travels with "
       "the design like any other part.")
d.body("Two limits are stated plainly. A part added this way draws as its stated footprint — a horn "
       "is a rectangular block on the workspace until its real geometry is curated into a later "
       "catalog. And the rendered snapshot omits a part whose geometry the application does not "
       "carry. The workspace and the 3D view draw every part from its stated shape and are "
       "unaffected.")

d.heading("What Does Not Change")
d.body("Existing .library, .parts, .kit, and .block files open unchanged; the file format gains "
       "fields and loses none. Jo Watts's curated student library remains the course's starting "
       "palette, with the catalog standing behind it as the reference shelf. No server change is "
       "involved: the catalog is data, and the search, the marker, and Add Part are page work. The "
       "library is a Blocks concept with no counterpart in Sangala Studio or Sangala Mosaic, so no "
       "cross-application alignment is disturbed.")

d.heading("Decisions the Proposal Leaves Open")
d.body("Four choices:", before_list=True)
d.step("The catalog's scope: parts Pick a Brick currently stocks, or the full ordinary families "
       "with unstocked parts marked. Stock changes; a marked catalog ages better.")
d.step("Whether the catalog loads when the application opens or is opened by hand like any other "
       "library.")
d.step("Whether Add Part requires the element ID, or accepts a part that designs without ordering "
       "and is flagged at export.")
d.step("The word itself: whether the interface says catalog, or simply treats it as a larger "
       "library.")
d.body("The natural sequence is the catalog first — it removes most of the demand and needs no new "
       "interface beyond the search field — with Add Part following. Both are page and tooling work "
       "for after the current freeze clears.")

print(d.save(OUT, "Getting Bricks into the Library"))
